<?php

namespace Helios\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
  public function getSelectList()
  {
    $qb = $this->createQueryBuilder('a')
               ->where('a.publication = 1');

    return $qb;
  }

  public function getArticles($blog, $nombreParPage, $page)
  {
    if ((int) $page < 1) {
      throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
    }

    $query = $this->createQueryBuilder('a')
                  ->leftJoin('a.image', 'i')
                    ->addSelect('i')
                  ->leftJoin('a.categories', 'cat')
                    ->addSelect('cat')
                  ->leftJoin('a.articleCompetences', 'ac')
                    ->addSelect('ac')
                  ->leftJoin('ac.competence', 'c')
                    ->addSelect('c')
                  ->leftJoin('a.user', 'u')
                    ->addSelect('u')
                  ->where('a.publication = 1')
                  ->andWhere('u.username = :blog')
                    ->setParameter('blog',$blog)
                  ->orderBy('a.date', 'DESC')
                  ->getQuery();

    $query->setFirstResult(($page-1) * $nombreParPage)
          ->setMaxResults($nombreParPage);

    return new Paginator($query);
  }

    public function getArticlesTag($tag)
    {

        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.categories', 'cat')
            ->addSelect('cat')
            ->leftJoin('a.articleCompetences', 'ac')
            ->addSelect('ac')
            ->leftJoin('ac.competence', 'c')
            ->addSelect('c')
            ->leftJoin('a.user', 'u')
            ->addSelect('u')
            ->where('a.publication = 1')
            ->where('cat = :tag')
            ->setParameter('tag',$tag)
            ->orderBy('a.date', 'DESC')
            ->getQuery();

        return $query;
    }
}
