<?php

namespace Helios\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function filter($tags) {
        $names = array();
        $flatTags = array();

        foreach ($tags->toArray() as $k => $tag) {
            if (in_array($tag->getTag(), $flatTags)) {
                $tags->remove($k);
                continue;
            }

            $flatTags[] = $tag->getTag();

            if ($tag->getId() === null) {
                $names[$k] = $tag->getTag();
            }
        }

        if (!$names) {
            return;
        }

        $qb = $this->createQueryBuilder('t');
        $tagsInDB = $qb->where($qb->expr()->in('t.tag', $names))
            ->getQuery()
            ->getResult();

        foreach ($tagsInDB as $tag) {
            $tags->remove(array_search($tag->getTag(), $names));
            $tags->add($tag);
        }
    }

    public function getByTag($tag)
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.tag = :tag')
            ->setParameter('tag',$tag);

        return $qb;
    }
}
