<?php

namespace Helios\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThumbUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThumbUpRepository extends EntityRepository
{
}
