parameters:
#    helios_manager.example.class: Helios\ManagerBundle\Example

services:
#    helios_manager.example:
#        class: %helios_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]